[theme]
primaryColor = "#4da6ff"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2E2E2E"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
